export const schema = {
  FULL_NAME: "fullName",
  GENDER: "gender",
  EMAIL: "email",
  BODY_WEIGHT: "bodyWeight",
  BIRTH_DATE: "birthDate",
  ADDRESS: "address",
  PHONE_NUMBER: "phoneNumber",
  PEDIGREE_CHART: "pedigreeChart",
  ADMITTOR_NAME: "admittorName",
  ADMISSION_DATE: "admissionDate",
  PARENTS_SEPARATED: "parentsSeparated",
  PARENTS_SEPARATED_DESCRIPTION: "parentsSeparatedDescription",
  PARENTS_DIVORCED: "parentsDivorced",
  PARENTS_DIVORCED_DESCRIPTION: "parentsDivorcedDescription",
  PARENTS_DIED: "parentsDied",
  PARENTS_DIED_DESCRIPTION: "parentsDiedDescription",
  STEP_FAMILY: "stepFamily",
  STEP_FAMILY_DESCRIPTION: "stepFamilyDescription",
  DOCTOR_NOTES: "doctorNotes",
  DIAGNOSIS_TREATMENT: "diagnosisTreatment",
};
